---
apiVersion: v1
kind: Service
metadata:
  name: service-webapp
  namespace: webapp
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 32112
  type: NodePort
  selector:
    app.kubernetes.io/name: webapp
    version: v2
